kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 3000
        hostPort: 3000
      - containerPort: 3333
        hostPort: 3333
      - containerPort: 9090
        hostPort: 9090